sonar.projectKey=LopataInKramp_sport_betting
sonar.organization=lopatainkramp
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info